// <auto-generated />
using System;
using DBconnect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBconnect.Migrations
{
    [DbContext(typeof(MyDBcontext))]
    [Migration("20250308164905_Products_fix_1.0.2")]
    partial class Products_fix_102
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBconnect.Models.CategoriesEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DBconnect.Models.PopularCategoriesEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("PopularCategories");
                });

            modelBuilder.Entity("DBconnect.Models.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriesEntityCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PopularCategoriesEntityCategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoriesEntityCategoryId");

                    b.HasIndex("PopularCategoriesEntityCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DBconnect.Models.ProductEntity", b =>
                {
                    b.HasOne("DBconnect.Models.CategoriesEntity", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoriesEntityCategoryId");

                    b.HasOne("DBconnect.Models.PopularCategoriesEntity", null)
                        .WithMany("Products")
                        .HasForeignKey("PopularCategoriesEntityCategoryId");
                });

            modelBuilder.Entity("DBconnect.Models.CategoriesEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DBconnect.Models.PopularCategoriesEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
